#!/bin/bash 
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N OPENMP
#PBS -joe
#PBS -o OUT+$PBS_JOBID
#PBS -q teaching
#PBS -l nodes=1:ppn=8,walltime=00:05:00

#! Mail to user if job aborts
#PBS -m a

#! Full path to application + application name
application="./parallel_shared_pi.exe"

#! Run options for the application
options=""

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`
 
numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the executable
time $application $options

